# .github/workflows/resolve-conflicts.yml
name: Resolve Conflicts

on:
  push:
    branches:
      - main  # Add other base branches if needed (master, develop, etc.)
  workflow_dispatch: # To trigger from action
    inputs:
      action:
        description: 'Action name'
        required: true
        default: "resolve-conflicts"
      prNumber:
        description: "PR number"
        required: true

jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Junie
        id: junie
        uses: JetBrains/junie-github-action@main
        with:
          junie_api_key: ${{ secrets.JUNIE_API_KEY }}
          resolve_conflicts: true

      - name: Print output
        run: cat newfile.txt

      - name: Print commits
        run: git log -n 10

      - name: Upload project working directory as artifact
        if: always() && steps.prepare.outputs.SHOULD_SKIP != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: project-working-directory
          path: |
            ${{ github.workspace }}
          retention-days: 7
          if-no-files-found: warn
          include-hidden-files: true